lakehouse_dbt:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-iceberg
      port: 10000
      user: spark
      schema: silver
      connect_retries: 3
      connect_timeout: 60
